### ISSUE TITLE
(Multi Account Dashboard): (Show logs from diff accounts in the same dashboard)

### ISSUE THREAD

**Issue by wanggold** [aws-solutions/centralized-logging-with-opensearch#106]
### Describe the feature

We would like to have a feature where the logs from multiple accounts can be shown in the same dashboard on central account via centralized logging with OpenSearch. 

### Use Case

For example, the CLO of a central account imports CloudFront logs from two accounts (A1, A2). The customer wants a dashboard where the request charts for A1 and A2 can appear on one dashboard. In this way, the Request History bar chart can have two legends - one for A1's request count and the other for A2's request count.

<img width="1256" alt="Screen Shot 2023-04-14 at 2 20 37 PM" src="https://user-images.githubusercontent.com/2307322/231961741-6fe8699a-d732-4180-b818-31d4a54ed68c.png">

### Solution version used

v1.0.0

**Comment by JoeShi** [comment]
I am assuming you are trying to merge logs in the same format into the dashboard. To achieve this, you can ingest the same format of logs (e.g., CloudFront access logs) into the same index. Here are some ways to do this, and we plan to make it easier in future versions.

## Step 1: Ingest logs into the same index (same dashboard).
There are two ways to ingest logs from multiple resources into the same index. The first one create less resources, and the second one is more automatic. The cost is same for both approach.

### Approach 1: Put logs under the same prefix on S3, and create one log ingestion pipeline
Assume you want to save all CloudFront logs in the same S3 bucket (logging bucket). And the logging bucket is in the same region and same AWS account as the CLO solution.

1. Configure the CloudFront distribution in account A. For example, you can specify the prefix as `clo/cloudfront/<account-a-id>/`
2. Configure the log output for CloudFront distribution in account B, and save to the same prefix, for example `clo/cloudfront/<account-b-id>/`
3. Create an CloudFront log ingestion pipeline on the CLO console, and choose **Manual** when you select the CloudFront distribution.
4. Input an identifier in the **CloudFront Distribution ID**, it is just used for identification purpose. For example,`merged-logs`.
5. In **CloudFront Standard Log location**, input the prefix which includes both of your CloudFront distributions logs, for example, `s3://logging-bucket/clo/cloudfront/`. Please remember to replace logging bucket and the prefix with your own value.
<img width="1147" alt="Screen Shot 2023-04-17 at 11 04 11" src="https://user-images.githubusercontent.com/2173635/232368102-86b47555-4741-4a03-b306-591a08e5a9a1.png">

By using this approach, you can ingest logs belongs to multiple CloudFront into the same index, and use the same dashboard to visualize the logs.

### Approach 2: Use multiple log ingestion pipeline, and put logs in the same index in OpenSearch.
Assume you have followed the [cross-account ingestion](https://docs.aws.amazon.com/solutions/latest/centralized-logging-with-opensearch/cross-account-ingestion.html), and imported multiple logs.

1. Create an CloudFront log ingestion pipeline on the CLO console for CloudFront A, and choose **Automatic**. The CLO will detect the log location of the CloudFront automatically, and if the log output is not enabled, it will allow you to enable the standard logs.
2. In the **Step 3: Specify OpenSearch domain**, click to expand the **Additional settings**. 
3. Change the value for **Index Prefix**. For example, `merged-logs`.
4. Create the log ingestion pipeline for CloudFront A.
5. Create another CloudFront log ingestion pipeline for CloudFront B. Please do not forget to select the right account in **Step 1: Specify settings**.
6. In **Step 3: Specify OpenSearch domain*, choose **No** for Sample dashboard.
7. expand the **Additional settings**, and input the sample value in **Index Prefix**. For example, `merged-logs`.
8. Create the log ingestion pipeline for CloudFront B.
<img width="776" alt="Screen Shot 2023-04-17 at 11 26 23" src="https://user-images.githubusercontent.com/2173635/232370927-c7ae8c60-dacd-437f-ab72-0f2da00d8ec0.png">

By using the above approach, you create multiple log ingestion pipelines and upload logs in the sample index (same dashboard) in OpenSearch.

## Step 2: Add filter in the dashboard
If you want to filter logs only belongs to one CloudFront distribution, you should consider add some filters in the built-in dashboard. 

1. Open the OpenSearch Dashboards, and find the dashboard created by CLO. 
2. Click the **Edit** button on the top right corner, and choose **Create new**.
3. Choose **Controls** from the popup window.
4. On the Controls panel, select **Option list**, and click the **Add** button.
5. Input a value for **Control Label**.
6. Select the corresponding Index Pattern. The CLO has already created that for you. For example `merged-logs-cloudfront-*`.
7. Select `cs-host.keyword` in the **Field**.
8. Click the **Update** button at the right bottom corner.
<img width="502" alt="Screen Shot 2023-04-17 at 11 50 20" src="https://user-images.githubusercontent.com/2173635/232373801-073fb663-ffd7-4edd-9384-ebbd230cb35f.png">
9. Select the **Save**, button, and input a title value for the visualization.
10. By default, the visualization will be appended to the bottom of the dashboard. We recommend you to drag to the up. 
<img width="1475" alt="Screen Shot 2023-04-17 at 11 53 12" src="https://user-images.githubusercontent.com/2173635/232374018-2f99b330-c2d7-432f-9390-3bbcbabd166a.png">

**Comment by wanggold** [comment]
Can I ask where `cs-host.keyword` is defined in **Step 2:7**?

**Comment by JoeShi** [comment]
Hi, @wanggold. When you create the CloudFront log analytics pipeline, you have an option to create a pre-defined CloudFront monitoring dashboard. If you enable this option, the solution will help to you create those definitions, including index mapping template, visuals, dashboard.
