### ISSUE TITLE
WAF Logs:  Need to support log filter for AWS WAF logs

### ISSUE THREAD

**Issue by readybuilderone** [aws-solutions/centralized-logging-with-opensearch#114]
### Describe the feature

LogHub now supports full WAF logs and Sampled WAF logs, which is great, but because of the underlying AWS API, certain fields are confirmed in the Sampled WAF Log. 
Users want to use the structure in the Full WAF Log, but want to be able to specify the sampling rate in Lambda to reduce the amount of logs going into OpenSearch, thus reducing the cost of the overall solution.

### Use Case

The filtering sampling feature is especially needed in scenarios where the volume of WAF logs will become huge and costly when users are under constant attack.

### Solution version used

v1.1.1

**Comment by James96315** [comment]
You can use the following workarounds:
#### 1.In the CloudFormation resource of the WAF pipeline, search for the Lambda function with the keyword "LogProcessorFn"
#### 2.Click on the link to open the Lambda Function console
#### 3.import random
#### 4.Replace line 316 with the following:
```
    sampling_quantity=100
    sampled_rows=random.sample(range(1, batch_size), sampling_quantity)
    line_counter=0
    for line in read_file(key):
        line_counter += 1
        if line_counter not in sampled_rows:
            continue
```
