### ISSUE TITLE
(Observability): Ability to surface errors of shard number are full in the AOS domain

### ISSUE THREAD

**Issue by luorobin-a2z** [aws-solutions/centralized-logging-with-opensearch#118]
### Describe the feature

Provide alarms or notification when the shard number are full or exceeding limit in the AOS domain.

### Use Case

Some times log are not ingested due to the shard number exceed the limit of AOS, but this error are hard to identify as the error logs are not in the log processor lambda logs in CloudWatch logs.

### Solution version used

1.0

**Comment by JoeShi** [comment]
We have add the metrics, logging and alarms of pipelines. If the customer enabled the alarms when creating pipelines, they should be able to receive alarms through SNS now.
