### ISSUE TITLE
LogPipelinelogBucketNotifications183A08DA: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Unable to validate the following destination configurations

### ISSUE THREAD

**Issue by SeagullTian** [aws-solutions/centralized-logging-with-opensearch#12]
### Describe the bug

Face following error during the deployment:

Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Unable to validate the following destination configurations

Logical ID: LogPipelinelogBucketNotifications183A08DA

May I ask if there's any insight how to solve this problem?

Thanks in advance. 

### Expected Behavior

Make this deployment work

### Current Behavior

Deployment Failure with error:

Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Unable to validate the following destination configurations

### Reproduction Steps

Use the Template for China Region and it will face the error 

### Log Hub Version

N/A

### AWS Region. e.g., us-east-1

cn-north-1

**Comment by YikaiHu** [comment]
Hi @SeagullTian , could you please check the region of your log source bucket? It should be the same as your Log Hub deploy region (cn-north-1). 
This error log seems like caused by the failure of S3 notification creation.

**Comment by SeagullTian** [comment]
Thanks Kervin for checking. I can confirm that the source bucket is in the same region:
***@***.***

Best Regards,
Yifeng Tian

**Comment by YikaiHu** [comment]
Hi @SeagullTian , what's the type of the Log in this pipeline?  
And can you provide the earliest error message in CloudFormation Stack's event?

**Comment by SeagullTian** [comment]
WAF Log, I'm not sure if this is what you ask for. 

as you can see, the error I shared is the earliest one. 
![image](https://user-images.githubusercontent.com/109660531/179952713-bcc0bb96-bcd7-4fd6-8fbe-1b163d95d6ea.png)

i also tried to check the CloudWatch log but it seems useless:
![image](https://user-images.githubusercontent.com/109660531/179953455-02c3c47e-b806-4efd-8485-c171acc6acce.png)

**Comment by SeagullTian** [comment]
Thanks @YikaiHu for the update. 

1. May i ask if there's an ETA for this issue?
2. Where can i find this LogHub Console to do the manual setup? I'm still new to LogHub

**Comment by SeagullTian** [comment]
May i ask if there's an ETA for the fix? Even I tried to create the S3Notification manually in Management Console does NOT help.
![image](https://user-images.githubusercontent.com/109660531/180149217-9c69aca7-a678-4c78-b550-24c51704305b.png)

Currently, I'm not able to use LogHub console to recreate a pipeline. Please let me know if there's any other way we can do this.

**Comment by owenCCY** [comment]
Hi @SeagullTian, thanks for your info and we have added this issue in our backlog. For now, this issue can not be fixed and we are also waiting for CDK team's update. Sorry for the inconvenience, I will end this thread for now.

**Comment by wchaws** [comment]
Root cause: https://github.com/aws/aws-cdk/issues/18090#issuecomment-1853374393

**Comment by JoeShi** [comment]
We changed to EventBridge in v2.3, no longer exists
