### ISSUE TITLE
Instance should not be added to the same Instance Group

### ISSUE THREAD

**Issue by JoeShi** [aws-solutions/centralized-logging-with-opensearch#128]
### Describe the bug

Currently, I can add the instance to an Instance Group which already contains that instance. 

### Expected Behavior

The user interface should filter out those instances.

### Current Behavior

The UI displays those instances, and i can add the instance to the Instance Group. Although, the instance group detail page will now show the instance twice, but I can conduct this action without any error message.

### Reproduction Steps

1. Go to the Instance Group Detail page
2. Select the instances
3. Click the Add button

### Possible Solution

Filter out instances which are already contained by the same Instance Group. 

### Solution Version

v1.0.1

**Comment by evalzy** [comment]
Fixed in V2.1.1
