### ISSUE TITLE
New VPC with 1 NAT option

### ISSUE THREAD

**Issue by frank622** [aws-solutions/centralized-logging-with-opensearch#131]
### Describe the feature

Importing OpenSearch, if selecting to create a new VPC, it will generate 2 NATs and require 2 EIPs. Some scenarios do not require high availability, only one is needed.

### Use Case

Importing OpenSearch, if selecting to create a new VPC, it will generate 2 NATs and require 2 EIPs. Some scenarios do not require high availability, only one is needed.

### Solution version used

1.0.1

**Comment by JoeShi** [comment]
Customer can launch the solution with existing VPC
