### ISSUE TITLE
EKS: fails cross-account cluster import due to OICD provider

### ISSUE THREAD

**Issue by mavogel** [aws-solutions/centralized-logging-with-opensearch#135]
### Describe the bug

When I tried to import an EKS cluster from another account, here with the id `111111111111` (did not test with the same account), I got a modal popping up saying `The was an error in the lambda function, please look at the logs` in the account where the `centralized-logging-with-opensearch` (clwo) solution is running (account id `99999999999`)

### Expected Behavior

1. the modal should tell me which lambda function in which account fails (e.g. providing the arn) or provide a link to the lambda function (it took me some time to find which lambda, in which account, had the error log)
2. the import of the cluster should work by default

### Current Behavior

permission denied in CLW log group `/aws/lambda/<prefix>-main-EKSClusterStackEKSClusterLogSourceHandle-<suffix>` of the lambda in account `99999999999`

```console
2023-06-21T12:25:00.442+02:00
[ERROR]	2023-06-21T10:25:00.442Z	5bcbbfaa-8b29-45e7-9b54-863813ca866c	An error occurred (AccessDenied) when calling the CreateOpenIDConnectProvider operation: User: arn:aws:sts::111111111111:assumed-role/clwo-add-member-account-CrossAccountRoleFACE29D1-14QZ8N039X9EJ/LogHubAcctAppLog is not authorized to perform: iam:CreateOpenIDConnectProvider on resource: arn:aws:iam::111111111111:oidc-provider/oidc.eks.us-east-1.amazonaws.com because no identity-based policy allows the iam:CreateOpenIDConnectProvider action
```

### Reproduction Steps

You have `clwo` setup in account `99999999999`, add member account `111111111111`, create an EKS cluster in account `111111111111`, which has an OICD provider attached by default, and try to import it via the clwo UI.

I am using the EKS cluster from this AWS [workshop](https://catalog.us-east-1.prod.workshops.aws/workshops/1abb648b-2ef8-442c-a731-efbcb69c1e1e/en-US/030-step1).

### Possible Solution

This worked for me: the policy of the `<prefix>-add-member-account-CrossAccountRole-<suffix-id>` in the account `111111111111` should have the `iam:CreateOpenIDConnectProvider` action in the following IAM policy statement
```json
{
            "Action": [
                  "iam:GetOpenIDConnectProvider", 
                  "iam:CreateOpenIDConnectProvider"
             ],
            "Resource": "arn:aws:iam::111111111111:oidc-provider/oidc.eks.*",
            "Effect": "Allow",
            "Sid": "EKSPolicy1"
}
```

### Solution Version

`v1.0.1`

### AWS Region. e.g., us-east-1

`us-east-1`

**Comment by James96315** [comment]
just fixed it.

**Comment by YikaiHu** [comment]
Fixed in https://github.com/aws-solutions/centralized-logging-with-opensearch/releases/tag/v1.0.3
