### ISSUE TITLE
CLO:nonterminate filter: ratelimit rule matched label . when filter with non-terminate action =count. 

### ISSUE THREAD

**Issue by alexcui2010** [aws-solutions/centralized-logging-with-opensearch#137]
### Describe the bug

OpenSearch: ratelimit rule matched label . when filter with non-terminate action =count. The number mismatch.
In therory, ratelimit rule matched label should have WAF rule count . While if we search through CLO dashboard, the non-terminate action =count request is less. 
In our case, there are around 32k requests has ratelimit label . while only 504 requests matched with non-terminate action =count.

### Expected Behavior

ratelimit rule label matched request number with with requests with non-terminate action =count. 

### Current Behavior

In our case, there are around 32k requests has ratelimit label . while only 504 requests matched with non-terminate action =count.

### Reproduction Steps

Create a waf rate limit rule. Send requests exceed the requests rate. We will have the request exceed rate marked with label.
Then we can check labeled request volume and non-terminate action=count request  volume. If they are mismatch, we will have the reproduce.

### Solution Version

1.21

**Comment by James96315** [comment]
Please refer to this link.

**Comment by JoeShi** [comment]
duplicate with #136
