### ISSUE TITLE
Json log missing - due to fields format changing

### ISSUE THREAD

**Issue by evalzy** [aws-solutions/centralized-logging-with-opensearch#143]
### Describe the feature

Customer Json log partially lost, stored in backup bucket. After deep dive, it's come up to the jason fields format has been changed. 

### Use Case

When the Json fields format changes, it's leading that log partially lost. 

### Proposed Solution

Workaround: adjust the index template, setting the changed fields can not be index in the opensearch. 

### Solution version used

V1.2.0

**Comment by JoeShi** [comment]
For JSON logs, we will ingest all unconfigured fields.
