### ISSUE TITLE
Cannot differentiate the Lambda for different AWS Service log pipeline based on  Lambda description 

### ISSUE THREAD

**Issue by JoeShi** [aws-solutions/centralized-logging-with-opensearch#146]
### Describe the bug

The currently created CloudWatch Logs-based logs (RDS) or Kinesis Data Streams-based logs (CloudFront real-time logs) all appear to use the same lambda description for processing Kinesis logs. It is difficult for customer to differentiate them.

For other service logs, the log type is displayed, so it is recommended to include corresponding information.

### Expected Behavior

Use different description for different AWS service log ingestion Lambda processor.

### Current Behavior

N/A

### Reproduction Steps

N/A

### Solution Version

v1.0.3

**Comment by bcambs09** [comment]
Please 🙏 I'm having trouble keeping track of the resources that are getting created

**Comment by JoeShi** [comment]
Sure. we are working on it.
