### ISSUE TITLE
Syslog: Fix port conflict when adding & deleting new log source parallel 

### ISSUE THREAD

**Issue by wchaws** [aws-solutions/centralized-logging-with-opensearch#174]
### Describe the bug

```
Resource handler returned message: "A listener already exists on this port for this load balancer 'arn:aws:elasticloadbalancing:us-east-2:******:loadbalancer/net/LogHub-syslog-nlb/ba269ebe02dfc35c' (Service: ElasticLoadBalancingV2, Status Code: 400, Request ID: 2d8aaab6-5127-461c-ad6a-9382bc233747, Extended Request ID: null)" (RequestToken: 95eba119-1260-0da5-d0d9-92f95c5dd2b5, HandlerErrorCode: AlreadyExists)
```

### Expected Behavior

everything works fine

### Current Behavior

error

### Reproduction Steps

- Create an APP Pipeline and set up a syslog ingestion with the recommended port.
- While deleting the previously created syslog ingestion, create a new syslog ingestion using the system's automatically recommended port.
- However, it was observed that the newly created ingestion failed to be created successfully.

### Possible Solution

Root Cause:
During the ingestion creation process, the recommended port was the port of an ingestion that was currently being deleted.

### Solution Version

v1.0.3

**Comment by JoeShi** [comment]
fixed in v2 https://github.com/aws-solutions/centralized-logging-with-opensearch/releases/tag/v2.0.0
