### ISSUE TITLE
EKS logs: Not matched ISM Policy timestamp field

### ISSUE THREAD

**Issue by Paul-AWS** [aws-solutions/centralized-logging-with-opensearch#181]
### Describe the bug

The timestamp_field of cold transition in ISM policy is @timestamp while the time_key in DeamonSet Fluent-bit json file is time. The mismatches of these two field will cause error in status transition.

### Expected Behavior

The time_key of DeamonSet Fluent-bit json file should match with the timestamp_field in ISM policy.

### Current Behavior

The time_key of DeamonSet Fluent-bit json file is not matched with the timestamp_field in ISM policy.

### Reproduction Steps

Create an EKS pipeline using DeamonSet mode, with cold layer.

### Solution Version

1.0.3

**Comment by JoeShi** [comment]
fixed in v2.1.0
