### ISSUE TITLE
KDS Buffer Auto Scaling: KDS to increase rapidly and can not scaling down

### ISSUE THREAD

**Issue by YikaiHu** [aws-solutions/centralized-logging-with-opensearch#183]
### Describe the bug

The settings for KDS AutoScaling are overly sensitive, causing the number of shards for KDS to increase rapidly and preventing scaling down.

### Expected Behavior

Scaling up and down based on customer's workload.

### Current Behavior

The settings for KDS AutoScaling are overly sensitive, causing the number of shards for KDS to increase rapidly and preventing scaling down.

### Reproduction Steps

Reproduce by having the data source consistently generate over 1000 logs per second.

### Solution Version

v1.0.3

**Comment by JoeShi** [comment]
fixed in v2.0
