### ISSUE TITLE
CLO:opensearch proxy enable

### ISSUE THREAD

**Issue by MasonsDad** [aws-solutions/centralized-logging-with-opensearch#188]
### Describe the bug

启用AOS的proxy后，无法访问，检查了Target group后，健康检查一直不通过

### Expected Behavior

能够正常通过proxy访问dashboard

### Current Behavior

启用AOS的proxy后，无法访问，检查了Target group后，健康检查一直不通过

### Reproduction Steps

启用proxy

### Solution Version

2.0.0

### AWS Region. e.g., us-east-1

cn-northwest-1

**Comment by James96315** [comment]
@MasonsDad ,方便提供一下详细的网络信息吗？另外，需要注意选择的私有子网要有NAT gateway, Public Security Group可以选择Proxy Access Security Group。
可以参考这个文档：https://docs.aws.amazon.com/solutions/latest/centralized-logging-with-opensearch/access-proxy-1.html

**Comment by JoeShi** [comment]
Close as we did not hear feedback from you for a long time. Please open another ticket if you need further assistant.
