### ISSUE TITLE
Access proxy: the parameters in the documentation is not consistent with the parameters in CloudFormation

### ISSUE THREAD

**Issue by JoeShi** [aws-solutions/centralized-logging-with-opensearch#189]
### Describe the issue

<img width="1167" alt="Screen Shot 2023-09-01 at 09 46 47" src="https://github.com/aws-solutions/centralized-logging-with-opensearch/assets/2173635/a20c528b-553e-499c-a214-0c9c76d4542f">
<img width="1156" alt="Screen Shot 2023-09-01 at 09 47 05" src="https://github.com/aws-solutions/centralized-logging-with-opensearch/assets/2173635/66a4f703-5042-41a4-89da-3b3f52682b6a">
<img width="707" alt="Screen Shot 2023-09-01 at 09 48 14" src="https://github.com/aws-solutions/centralized-logging-with-opensearch/assets/2173635/02146eac-be21-42a2-aa30-85ba58ca6177">

### Links

https://aws-solutions.github.io/centralized-logging-with-opensearch/en/implementation-guide/domains/proxy/#using-the-cloudformation-stack
https://docs.aws.amazon.com/solutions/latest/centralized-logging-with-opensearch/access-proxy-1.html#create-a-proxy

**Comment by evalzy** [comment]
Fixed in Version 2.1
