### ISSUE TITLE
Sample log parsing: Support unix time format for data ingestion

### ISSUE THREAD

**Issue by victzero** [aws-solutions/centralized-logging-with-opensearch#198]
### Describe the feature

**Sample Log for ingestion:**
```
{"topic": "jp/xxx-protect/ef0b3502bfca/alert", "timestamp": 1694697891449, "region": "us-east-1"}
```

**Request**
Need to support unix time format for data ingestion

### Use Case

Ingest log from jamf-protect.

### Solution version used

Version : v1.0.3

**Comment by James96315** [comment]
fixed in v2.2.0 https://github.com/aws-solutions/centralized-logging-with-opensearch/releases/tag/v2.2.0
