### ISSUE TITLE
OpenSearch version is not correct in the documentation

### ISSUE THREAD

**Issue by JoeShi** [aws-solutions/centralized-logging-with-opensearch#206]
### Describe the issue

Centralized Logging with OpenSearch supports Amazon OpenSearch Service, engine version OpenSearch 7.10 or later, and engine version OpenSearch 1.0 or later.

Amazon do not have OpenSearch v7.10.

### Links

https://docs.aws.amazon.com/solutions/latest/centralized-logging-with-opensearch/domain-operations.html

**Comment by evalzy** [comment]
Fix in Version 2.1.1
