### ISSUE TITLE
Need IIS logs support

### ISSUE THREAD

**Issue by oodogamazon** [aws-solutions/centralized-logging-with-opensearch#212]
### Describe the feature

CLO already has Nginx / Apache, but still a lot of users need IIS logs support.

Please add if can

### Use Case

CLO already has Nginx / Apache, but still a lot of users need IIS logs support.

### Other Information

Athena already has this function right now. 
https://docs.aws.amazon.com/zh_tw/athena/latest/ug/querying-iis-logs.html

### Solution version used

2.0

**Comment by James96315** [comment]
fixed in v2.2.0 https://github.com/aws-solutions/centralized-logging-with-opensearch/releases/tag/v2.2.0
