### ISSUE TITLE
(Deploy): CustomResource not authorized to perform: lambda:InvokeFunction on CRCRLambda3E918D98

### ISSUE THREAD

**Issue by AlbertMingXu** [aws-solutions/centralized-logging-with-opensearch#216]
### Describe the bug

When deploying the main stack, the creation of CRCRLambda3E918D98 failed due to lack of Lambda:Invoke permission.

This is an occasional problem and does not always occur.

### Expected Behavior

CRCRLambda3E918D98 should be CREATE_COMPLETE.

### Current Behavior

Received response status [FAILED] from custom resource. Message returned: User: arn:aws:sts::123456789012:assumed-role/clo-AWS679f53fac002430cb0da5b87ServiceRoleC-6M7fFaBGK31r/clo-AWS679f53fac002430cb0da5b87ServiceRoleC-JX13hYB6jKYj is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:eu-west-2:123456789012:function:clo-CRInitConfig61C535DA-PzPMT99ySWPM because no identity-based policy allows the lambda:InvokeFunction action (RequestId: c104f983-ce4a-44a4-96c4-fbe6003bbd76)

### Reproduction Steps

Deploy the main stack with CloudFormation.

### Solution Version

v2.0.0

### AWS Region. e.g., us-east-1

eu-west-2

**Comment by AlbertMingXu** [comment]
The cause of the problem may be that the role's permissions have not yet taken effect, causing the Custom Resource to fail to invoke CRCRLambda3E918D98.

You can solve this problem in the following ways.
1. Deploy the main stack with CloudFormation.
2. In the **Configure stack options** page where Stack is created, select **Stack failure options** -> **Preserve successfully provisioned resources**.
3. If the stack creation fails, click **Retry** to complete the stack creation.

**Comment by JoeShi** [comment]
Unable to reproduce the issue in latest version
