### ISSUE TITLE
Solution Cost: have the place in AWS to check all the cost generated by solution  

### ISSUE THREAD

**Issue by evalzy** [aws-solutions/centralized-logging-with-opensearch#228]
### Describe the feature

check the cost for solution related

### Use Case

I have no idea how much i paid for the solution related AWS services

### Solution version used

V2.1

**Comment by JoeShi** [comment]
We have added a default tag to all resourced provisioned by this solution https://github.com/aws-solutions/centralized-logging-with-opensearch/issues/285. And we have implemented a tag propagation feature when creating pipeline. You can view all cost in Cost Explorer. https://docs.aws.amazon.com/solutions/latest/centralized-logging-with-opensearch/cost.html#view-cost-in-cost-explorer
