### ISSUE TITLE
Tag propagation to AWS resources when adding tags to pipelines

### ISSUE THREAD

**Issue by JoeShi** [aws-solutions/centralized-logging-with-opensearch#232]
### Describe the feature

Propagate the tags to underlying AWS resources when creating pipelines with tags.

### Use Case

As a customer, I want to know the cost of each pipeline. 

### Solution version used

v2.1.1

**Comment by James96315** [comment]
fixed in v2.2.0 https://github.com/aws-solutions/centralized-logging-with-opensearch/releases/tag/v2.2.0
