### ISSUE TITLE
Light Engine: support ingest logs by choosing an S3 location

### ISSUE THREAD

**Issue by JoeShi** [aws-solutions/centralized-logging-with-opensearch#233]
### Describe the feature

Allow ingest custom application logs from an S3 location into Light Engine. 

### Use Case

With this feature, I can use to ingest logs from on-premise, other cloud providers, and unsupported AWS Service logs in CLO.

### Solution version used

v2.1.1

**Comment by James96315** [comment]
fixed in v2.2.0 https://github.com/aws-solutions/centralized-logging-with-opensearch/releases/tag/v2.2.0
