### ISSUE TITLE
Application Log: The S3 bucket automatically created by CLO solution as a log buffer area cannot receive application logs normally.

### ISSUE THREAD

**Issue by cabinhoo** [aws-solutions/centralized-logging-with-opensearch#237]
### Describe the bug

When configuring the EC2-based application log pipeline in Light-Engine, using the S3 bucket automatically created by the CLO scheme as the log buffer area, application logs cannot be received and processed normally.

### Expected Behavior

The configured buffer location and final storage log bucket location are both recorded in log files. Using athena to query the corresponding table also displays data.

### Current Behavior

Log files cannot be viewed in the configured log buffer S3 bucket and final log storage bucket, and the data in the corresponding database and table cannot be viewed using athena.

### Reproduction Steps

1.Use the light engine method to deploy an application log pipeline based on EC2, and select the CLO scheme for the buffer location to automatically generate an S3 bucket with a name containing staging.
2.Manually trigger or wait for the log file update to trigger the application log pipeline processing, wait for the step function to complete, and check whether there are new log files stored in the buffer bucket and the final log bucket.

### Possible Solution

For the buffer location, select other bucket created by  CLO or the bucket created by yourself.

### Solution Version

V2.1.1

### AWS Region. e.g., us-east-1

ap-south-1

**Comment by AlbertMingXu** [comment]
In version v2.1.1, do not use staging bucket as Log Buffer. You can use the default bucket in the buffer configuration, such as loggingbucket.

This problem will be fixed in v2.2.0.
