### ISSUE TITLE
[WAF Sampling]: CFN parameter interval default value should not be 1, or the deployment will not successful

### ISSUE THREAD

**Issue by owenCCY** [aws-solutions/centralized-logging-with-opensearch#240]
### Describe the issue

<img width="835" alt="image" src="https://github.com/aws-solutions/centralized-logging-with-opensearch/assets/43559574/a233eced-7d4d-494c-bdde-bef26c116aa9">

The interval value should be greater or equal to 2 and smaller or equal to 180.

### Links

https://docs.aws.amazon.com/solutions/latest/centralized-logging-with-opensearch/aws-waf-logs.html

**Comment by JoeShi** [comment]
The documentation has been updated.
