### ISSUE TITLE
Wrong warning message when creating pipeline with existing index in OpenSearch

### ISSUE THREAD

**Issue by JoeShi** [aws-solutions/centralized-logging-with-opensearch#260]
### Describe the bug

When I create the pipeline with a index prefix, and the new index is overlapped with an active index in OpenSearch, then it will show me the error message: `You have a deleted log pipeline that used this index prefix. If you keep creating this log pipeline will get mixed up.`. 

The pipeline is active, and not deleted.

### Expected Behavior

1. Change the error style popup window to warning style popup window.
2. Change Oops.. to Warning.
3. Change the text to `It looks like there is an active or deleted pipeline configured with the index you entered. To proceed with creating this new pipeline and sending logs to the same index, please select "Continue Create". If you would like to use a different index prefix instead, please choose "Edit" to update.`

### Current Behavior

N/A

### Reproduction Steps

N/A

### Solution Version

v2.1.0

**Comment by evalzy** [comment]
Fixed in v2.1.2
