### ISSUE TITLE
Log source Instance Group: Install log agent button is not installing the required log agent to the machines and not able to proceed further

### ISSUE THREAD

**Issue by mfwahid** [aws-solutions/centralized-logging-with-opensearch#264]
### Describe the bug

while i try to add an instance group in log source and try to select the listed instances and click install agent, nothing is happening and the instances are not turning online. It stays offline and not able to proceed from there.  

### Expected Behavior

Install agent should install the agent on the machines and turn online to proceed

### Current Behavior

Install agent is not installing the agent on ec2 machines

### Reproduction Steps

1. Click instance groups under log sources
2. select instances and click "Install Agent"

### Solution Version

(SO8025) - Centralized Logging with OpenSearch Solution. Template version workshop_v2.1.1

### Other information

Following the workshop "https://catalog.workshops.aws/centralized-logging-with-opensearch/en-US/ingest-logs-from-ec2"
please reach out to me on my alias "bdwahee@amazon.com"

**Comment by owenCCY** [comment]
Thanks for your feedback, we are aware of this issue, reproducing now

**Comment by owenCCY** [comment]
Hi, base on test, this issue has been resolved. Please have a try again.
If you find this issue still exists, please reopen this one, thx.
