### ISSUE TITLE
(CloudFront): The maximum number of distributions that can be displayed is 100 when creating pipeline.

### ISSUE THREAD

**Issue by AlbertMingXu** [aws-solutions/centralized-logging-with-opensearch#278]
### Describe the bug

The maximum number of distributions that can be displayed is 100 when creating pipeline. 

This issue results in the inability to select the desired distribution for log collection.

### Expected Behavior

When there are more than 100 distributions, the list can display all distributions and allow the creation of pipelines.

### Current Behavior

The maximum number of distributions that can be displayed is 100 when creating pipeline. 

### Reproduction Steps

Prerequisites:
1. There is a requirement for more than 100 distributions.

Steps:
1. Login the console
2. Choose **Log Analytics Pipelines** -> **AWS Service Logs**
3. Choose **Create a Pipeline**
4. Choose **CloudFront**
5. Choose **Next**
6. When you pull down the CloudFront Distribution menu, only 100 distributions are displayed in the list.

### Solution Version

v2.1.2

### AWS Region. e.g., us-east-1

us-east-1

**Comment by James96315** [comment]
fixed in v2.2.0  https://github.com/aws-solutions/centralized-logging-with-opensearch/releases/tag/v2.2.0
