### ISSUE TITLE
Added a default tag "CLOSolutionCostAnalysis" to all resources created by the solution

### ISSUE THREAD

**Issue by JoeShi** [aws-solutions/centralized-logging-with-opensearch#285]
### Describe the feature

Added a default tag "CLOSolutionCostAnalysis" to all resources created by the solution. Customers can view the entire cost of this solution in the Cost Explorer by tag.

### Use Case

View cost of the solution

### Solution version used

v2.1.0

**Comment by James96315** [comment]
fixed in v2.2.0 https://github.com/aws-solutions/centralized-logging-with-opensearch/releases/tag/v2.2.0
