### ISSUE TITLE
Reordered pipeline creation workflow: log type and analytics engine selection now occur first for AWS service

### ISSUE THREAD

**Issue by JoeShi** [aws-solutions/centralized-logging-with-opensearch#309]
### Describe the feature

On the first page of AWS service pipeline, allow customers to choose the log type and the desired log analytics engine (OpenSearch or Light Engine). In the rest of the wizard, the parameters or detailed configuration should be associated with the customer's choice on the first page. It is not associated in version v2.2.0

### Use Case

I am frustrated when I creating log pipeline, but the parameters are not associated with my choice on first page.

### Solution version used

v2.2.0

**Comment by fhoueto-amz** [comment]
.
