### ISSUE TITLE
Support Shield Advanced Logs

### ISSUE THREAD

**Issue by yourlin** [aws-solutions/centralized-logging-with-opensearch#49]
### Describe the feature

I expect that Log Hub can integrate Shield Advanced logs and providing a Dashboard for monitoring when a DDoS attack occurs. The attack source, traffic size, and attack times can be counted, and aggregated according to the attack source and attack method.

### Use Case

When a DDoS attack occurs, quickly identify the attack source and attack target.

### Log Hub version used

1.1.0

**Comment by JoeShi** [comment]
AWS Shield does not contain additional logs. The metrics can be viewed in CloudWatch Logs. And the API calling to AWS Shield are logged in CloudTrail. To analyze the API calling to Shield, it is recommended to ingest CloudTrail logs, and filter.
