### ISSUE TITLE
(RDS): (audit log only collects logs of QUERY type)

### ISSUE THREAD

**Issue by YikaiHu** [aws-solutions/centralized-logging-with-opensearch#52]
### Describe the bug

Currently RDS pipeline only collects the logs of QUERY type audit log. It filters other types of logs, such as CONNECT.

### Expected Behavior

Collect all types of audit log.

### Current Behavior

It only collects the logs of QUERY type audit log. It filters other types of logs, such as CONNECT.

### Reproduction Steps

Enable the Audit log in RDS mysql 8.x.
Create a RDS Pipeline.

### Log Hub Version

v1.1.0

**Comment by JoeShi** [comment]
Resolve, we have fixed in recent releasse
