### ISSUE TITLE
(Upgrade Log Hub): Upgrading the stack now only takes three steps, but the document directory is still four steps

### ISSUE THREAD

**Issue by YikaiHu** [aws-solutions/centralized-logging-with-opensearch#58]
### Describe the issue

Upgrading the stack now only takes three steps, but the document directory is still four steps.

### Links

https://awslabs.github.io/log-hub/en/implementation-guide/upgrade/#step-1-update-the-cloudformation-stack

**Comment by JoeShi** [comment]
Close as fixed
