### ISSUE TITLE
 structuredClone is undefined

### ISSUE THREAD

**Issue by chenhaiyun** [aws-solutions/centralized-logging-with-opensearch#60]
### Describe the bug

Log Hub show an error with " structuredClone is undefined"  when I clicked the create button. as show below:
<img width="599" alt="image (3)" src="https://user-images.githubusercontent.com/7011985/205229813-dd3c5f79-e690-4fd9-8732-f2de0fd5edac.png">

### Expected Behavior

I hope the creation was successful.

### Current Behavior

show an error in web ui

### Reproduction Steps

Use this browser version to log in the Log Hub web console.
Chrome: < 98
Edge: < 98
Firefox: < 94
Opera: < 84
Safari: < 15.4

### Possible Solution

Upgrade the browser to the latest version.
<img width="796" alt="image (4)" src="https://user-images.githubusercontent.com/7011985/205230414-39d3e03f-34ae-4bfb-9621-21098f3da892.png">

### Log Hub Version

v1.2.0

### AWS Region. e.g., us-east-1

all-region

**Comment by JoeShi** [comment]
any solution for not upgrading the browser?

**Comment by chenhaiyun** [comment]
> any solution for not upgrading the browser?

Absolutely, we can implement the deep copy method, or import a third-party deep copy library. Do we need to fix it now with a patch?

**Comment by JoeShi** [comment]
Hi, @chenhaiyun have we fixed this issue?

**Comment by JoeShi** [comment]
The issue has been fixed.
