### ISSUE TITLE
Log Config: Support nested JSON format of logs

### ISSUE THREAD

**Issue by JoeShi** [aws-solutions/centralized-logging-with-opensearch#62]
### Describe the feature

As a customer, I would like to ingest nested JSON format of logs into the OpenSearch domains.

### Use Case

many applications output logs in JSON format, and many of them are nested JSON.

### Log Hub version used

v1.2.0

**Comment by chdavidjohn** [comment]
Supporting nested JSON to AOS is a critical feature
