### ISSUE TITLE
Support Multi-line text format for logs stored in S3

### ISSUE THREAD

**Issue by chdavidjohn** [aws-solutions/centralized-logging-with-opensearch#66]
### Describe the feature

Support multi line text & nested JSON format for logs stored in S3

### Use Case

Logs stored in S3 currently support only JSON and Single-line text. Many applications generate multi-line text logs and also nested JSON's and stored them in S3.  

### Log Hub version used

1.2.0

**Comment by JoeShi** [comment]
The requested feature to ingest nested JSON and multiple text formatted to OpenSearch ingestion is supported since v2.1.0
