### ISSUE TITLE
(Log Config): (配置Nginx log format生成的time_local的正则表达式的")"位置错误)

### ISSUE THREAD

**Issue by AlbertMingXu** [aws-solutions/centralized-logging-with-opensearch#68]
### Describe the bug

配置Nginx log format生成的time_local的正则表达式的")"位置错误，

生成的表达式：\[(?<time_local>\d+/\S+/\d+:\d+:\d+:\d+)\s+\S+\]
正确的表达式：\[(?<time_local>\d+/\S+/\d+:\d+:\d+:\d+\s+\S+)\]

由于生成表达式默认没有包含时区信息，导致采集数据到AOS时时区被当作+0000时区处理，如果用户实际时区非+0000时区，就会出现时间错误。

### Expected Behavior

正确的time_local的正则表达式应为：\[(?<time_local>\d+/\S+/\d+:\d+:\d+:\d+\s+\S+\)]

### Current Behavior

Nginx日志配置生成的time_local的正则表达式：\[(?<time_local>\d+/\S+/\d+:\d+:\d+:\d+)\s+\S+\]，解析出的time_local没有包含时区信息

### Reproduction Steps

1. 打开LogHub Console，进入log confs页面
2. 点击create a log conf
3. Config Name输入Nginx-example, Log Type 选择 Nginx
4. Nginx Format输入：log_format  main1 '[$time_local] \[$http_x_forwarded_for\] \[$status\] \[$body_bytes_sent\] \[$request_time\] \[$hostname\] \[$host\] \[$request_method\] \[$server_protocol\] \[$http_referer\] \[$request_body\] \[$http_user_agent\] \[$request_uri\] \[$http_oaid\] \[$http_vaid\] \[$http_aaid\] \[$http_appsystem\] \[$http_appversion\] \[$http_version\] \[$http_brandname\] \[$http_modelname\] \[$http_gpsadid\] \[$http_adjustid\] \[$http_idfa\] \[$http_idfv\] \[$http_pushload\] \[$http_countrycode\] \[$remote_addr\]';
5. Sample log输入： [19/Dec/2022:22:42:17 -0800] [-] [200] [9026] [0.057] [ip-172-31-30-157.us-west-2.compute.internal] [api.novelender.com] [POST] [HTTP/1.1] [-] [SvLK=dVaI4BI1w&awoW=HWZAxE4arORQxZqf5R9GgDe%2Bnz0XdZiqNJlv0BECpMnutwu11fpaa2Irjen8ocpNNYlt7LldOT3xdW0cWiwy4S5zYC9v5glPTB8QZu8ZcvDYOGFKvh5O71MVGV2lokT1t8lck1L3kmaH%2BSzv7Ab3MgDCDYKMYi9hdazUqlHqFRstQcHg0fHtU8yd9Clpmvhyvt1YgC6RuI1Tui3%2Fth7DKh2qP6hCS2oxGuku2P01iBqHDQ4lJwAU9VV02EGWabY68egvjlbOcImvY3m%2F1gfkRSlpnLyZx%2FKN3TMC6zDTHZV%2BrIAe%2FJn1%2FzFQFpYo8DRYdD%2B7PMFY%2FwmLO1A3g2c24%2FlcKuzx2wk5qucMKfGsZqwVvRqUa5dWsnbvOiGpt8L391XLyUS1LfQ%2Fc1XWvZYQpE%2FEhKHzANCjAkoHmB2xN%2BzkNs05kTltfZi59ZNMr%2Fsec434NIPfqmSpDrpjMh230WAsrqgJ7LHIKFruh%2BoNWpQRlnun1wnKNZK8ORiWQtYgBO9htouk37SZyFdRtK0XtvXLqIMFqLhXpzz1MpEBQ3LkWhtJWkSmr5ENFpqFtZij%2Bc7boZKmfpVD1y9MIt0ls7RDkyrA2LG3C%2FFmmI%2FcGiwDwSMUreaP42r%2Bvm%2FAfCoq&Yn7s=91NrYeCdN] [Mozilla/5.0 (Linux; Android 12; SM-A115F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36] [/get_content] [-] [-] [-] [android] [39] [3.8.3] [samsung] [SM-A115F] [44cfdaa3-995f-4b22-934b-824c9602a479] [70ff16a35316568d473634cb0ee78878] [-] [-] [-] [] [41.115.102.162]
6. 点击Parse Log，time_local的value为19/Dec/2022:22:42:17，缺少时区信息-0800

### Log Hub Version

v1.2.1

### AWS Region. e.g., us-east-1

us-east-1

**Comment by AlbertMingXu** [comment]
补充：用户配置nginx日志的Log Format时，[time_local]的"["和"]"不需要转义，但是其他字段的[]都需要转义，使用体验会产生疑惑，建议统一，要么都需要转义，要么都不需要转义。

**Comment by AlbertMingXu** [comment]
问题临时修复方法，是进入DDB，搜索LogConf，找到对应的LogConf配置，修改regularExpression字段即可，使用该Logconf重建Ingestion即可。

**Comment by JoeShi** [comment]
fixed in v2 https://github.com/aws-solutions/centralized-logging-with-opensearch/releases/tag/v2.0.0
