### ISSUE TITLE
Log Config: Time key in Fluent Bit config for Spring Boot should be time type instead of None

### ISSUE THREAD

**Issue by YikaiHu** [aws-solutions/centralized-logging-with-opensearch#71]
### Describe the bug

When using log hub to create a Sprint-boot ingestion, the time key in applog-parser.conf is None. As a result, the timestamp of the log is incorrectly parsed into a String in AOS.

### Expected Behavior

The time key in applog-parser.conf is `time`.

### Current Behavior

The time key in applog-parser.conf is None.

![image](https://user-images.githubusercontent.com/34271744/211606845-fbc74fee-e2a7-4900-a1a6-37222c99441b.png)

### Reproduction Steps

Follow the log hub workshop Sprint-boot part.

### Log Hub Version

v1.2.1

### AWS Region. e.g., us-east-1

us-west-2

**Comment by JoeShi** [comment]
fixed in v2 https://github.com/aws-solutions/centralized-logging-with-opensearch/releases/tag/v2.0.0
