### ISSUE TITLE
Monitor, Install and Configure Fluent Bit on Windows Server 2016/2019/2022 Instances 

### ISSUE THREAD

**Issue by JoeShi** [aws-solutions/centralized-logging-with-opensearch#76]
### Describe the feature

The Instance Group can only list out the Linux instances, and the solution can only monitor/install/configure Fluent Bit on Linux Instances. We are expecting the solution can support Windows OS as well.

### Use Case

Monitor, install and configure log agents on Windows instances automatically.

### Log Hub version used

v1.0.0

**Comment by owenCCY** [comment]
The recommended solution contains four steps:

1. Create a application log pipeline in Centralized Logging with OpenSearch Solution console
Take a note of the buffer destination you chose. (Ex, if you choose S3 as buffer, take a note of the s3 bucket name)

2. Download Fluent Bit agent from [Fluent Bit: Official Manual](https://docs.fluentbit.io/manual/installation/getting-started-with-fluent-bit). Choose the version that suit your platform.

3. Config the Fluent Bit agent to the correct output destincation
[Guide here](https://docs.fluentbit.io/manual/installation/windows)
The output destination should be the S3 bucket location.

4. Attach role / policy to your windows instances, example policy is shown ass follows:
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "VisualEditor0",
      "Effect": "Allow",
      "Action": "s3:GetObject",
      "Resource": [
        "arn:aws:s3:::centralizedlogging-clloggingbucketxxxxxxxxxxxxxxxxxxxxxx",
        "arn:aws:s3:::centralizedlogging-clloggingbucketxxxxxxxxxxxxxxxxxxxxxx/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "ssm:DescribeInstanceProperties",
        "ssm:UpdateInstanceInformation"
      ],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "ec2messages:GetEndpoint",
        "ec2messages:AcknowledgeMessage",
        "ec2messages:SendReply",
        "ec2messages:GetMessages"
      ],
      "Resource": "*"
    }
  ]
}`

**Comment by James96315** [comment]
fixed in v2.2.0 https://github.com/aws-solutions/centralized-logging-with-opensearch/releases/tag/v2.2.0
