### ISSUE TITLE
Log Config: Nginx log type fail to parse $time_iso8601

### ISSUE THREAD

**Issue by heichow** [aws-solutions/centralized-logging-with-opensearch#77]
### Describe the bug

When I create Log Config and select Nginx Log Type, I input `log_format main_format  '$time_iso8601';` in Nginx Log Format and `2023-03-14T11:10:23+00:00` in Sample Log. Error message then occur: `The verification failed. Make sure that the sample log matches the specified log_format.`

### Expected Behavior

The verification should succeed, and Parse Log with Key `time_iso8601` and Value `2023-03-14T11:10:23`.

### Current Behavior

Same as description above. 

### Reproduction Steps

<img width="784" alt="Screenshot 2023-03-17 at 12 06 51 AM" src="https://user-images.githubusercontent.com/31873682/225683428-924b0ff7-38c4-4bed-b87b-3814b3941ebd.png">

### Log Hub Version

1.2.1

**Comment by JoeShi** [comment]
fixed in v2 https://github.com/aws-solutions/centralized-logging-with-opensearch/releases/tag/v2.0.0
