### ISSUE TITLE
Log Agent Installation: Support of agent installation on AL2023 instances

### ISSUE THREAD

**Issue by owenCCY** [aws-solutions/centralized-logging-with-opensearch#88]
### Describe the bug

Unable to install log agent on AL2023 AMI.

### Expected Behavior

By following the implementation guide, the openssl should be able to install on instances, and the fluent-bit agent can get online after installation.

### Current Behavior

I can not install openssl on AL2023 AMI, and the instance status will never get Online.

### Reproduction Steps

Connect to AL2023 instance
`sodu yum install openssl11`
Then go to CLO console, click install log agent
The instance status will always be Offline

### Solution Version

1.0

**Comment by James96315** [comment]
AL2023 x86_64:
if you got "error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory" or "error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory", you can refer to the following steps to install openssl 1.1:

- wget https://europe.mirror.pkgbuild.com/core/os/x86_64/openssl-1.1-1.1.1.u-1-x86_64.pkg.tar.zst
- unzstd openssl-1.1-1.1.1.u-1-x86_64.pkg.tar.zst 
- tar -xvf openssl-1.1-1.1.1.u-1-x86_64.pkg.tar
- ln -s usr/lib/libcrypto.so.1.1 /usr/lib/libcrypto.so.1.1
- ln -s usr/lib/libssl.so.1.1 /usr/lib/libssl.so.1.1

**Comment by James96315** [comment]
AL2023 aarch64:

- wget https://eu.mirror.archlinuxarm.org/aarch64/core/openssl-1.1-1.1.1.t-1-aarch64.pkg.tar.xz
- xz --decompress openssl-1.1-1.1.1.t-1-aarch64.pkg.tar.xz
- tar -xvf openssl-1.1-1.1.1.t-1-aarch64.pkg.tar
- cp usr/lib/libcrypto.so.1.1 /usr/lib64/libcrypto.so.1.1
- cp usr/lib/libssl.so.1.1 /usr/lib64/libssl.so.1.1

**Comment by qmugnier** [comment]
Hi, to me the workaround should be avoided as much as possible. There are reasons why the ssl library, a core security feature of the os by the way, is being updated. 
To make sure you are using the latest ssl libraries usually the ones shiped with your os, here is my workaround:
- Trigger an install of fluentbit through the app
- Update the fluentbit agent "manually" (i mean with any other way than though the application) using your regular packet manager
- the status of the agent in the UI shall be updated to active after a few seconds.

**Comment by JoeShi** [comment]
Hi, @qmugnier for share your input on this issue. 

Yes. We agree the workaround should be avoided. We will have an update of this solution in August. and this issues has been mitigated.
